In [1]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path("../data/raw")

application = pd.read_csv(
    DATA_DIR / "application_train.csv"
)

bureau = pd.read_csv(
    DATA_DIR / "bureau.csv"
)

previous_application = pd.read_csv(
    DATA_DIR / "previous_application.csv"
)

In [2]:
print("Application:", application.shape)
print("Bureau:", bureau.shape)
print("Previous application:", previous_application.shape)

Application: (307511, 122)
Bureau: (1716428, 17)
Previous application: (1670214, 37)

In [3]:
application.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
application.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), object(16)
memory usage: 286.2+ MB

In [5]:
application.columns.tolist()

['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [6]:
bureau.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1716428 entries, 0 to 1716427
Data columns (total 17 columns):
 #   Column                  Dtype
---  ------                  -----
 0   SK_ID_CURR              int64
 1   SK_ID_BUREAU            int64
 2   CREDIT_ACTIVE           object
 3   CREDIT_CURRENCY         object
 4   DAYS_CREDIT             int64
 5   CREDIT_DAY_OVERDUE      int64
 6   DAYS_CREDIT_ENDDATE     float64
 7   DAYS_ENDDATE_FACT       float64
 8   AMT_CREDIT_MAX_OVERDUE  float64
 9   CNT_CREDIT_PROLONG      int64
 10  AMT_CREDIT_SUM          float64
 11  AMT_CREDIT_SUM_DEBT     float64
 12  AMT_CREDIT_SUM_LIMIT    float64
 13  AMT_CREDIT_SUM_OVERDUE  float64
 14  CREDIT_TYPE             object
 15  DAYS_CREDIT_UPDATE      int64
 16  AMT_ANNUITY             float64
dtypes: float64(8), int64(6), object(3)
memory usage: 222.6+ MB

In [7]:
bureau.columns.tolist()

['SK_ID_CURR',
 'SK_ID_BUREAU',
 'CREDIT_ACTIVE',
 'CREDIT_CURRENCY',
 'DAYS_CREDIT',
 'CREDIT_DAY_OVERDUE',
 'DAYS_CREDIT_ENDDATE',
 'DAYS_ENDDATE_FACT',
 'AMT_CREDIT_MAX_OVERDUE',
 'CNT_CREDIT_PROLONG',
 'AMT_CREDIT_SUM',
 'AMT_CREDIT_SUM_DEBT',
 'AMT_CREDIT_SUM_LIMIT',
 'AMT_CREDIT_SUM_OVERDUE',
 'CREDIT_TYPE',
 'DAYS_CREDIT_UPDATE',
 'AMT_ANNUITY']

In [8]:
previous_application.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1670214 entries, 0 to 1670213
Data columns (total 37 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   SK_ID_PREV                   1670214 non-null  int64
 1   SK_ID_CURR                   1670214 non-null  int64
 2   NAME_CONTRACT_TYPE           1670214 non-null  object
 3   AMT_ANNUITY                  1297979 non-null  float64
 4   AMT_APPLICATION              1670214 non-null  float64
 5   AMT_CREDIT                   1670213 non-null  float64
 6   AMT_DOWN_PAYMENT             774370 non-null   float64
 7   AMT_GOODS_PRICE              1284699 non-null  float64
 8   WEEKDAY_APPR_PROCESS_START   1670214 non-null  object
 9   HOUR_APPR_PROCESS_START      1670214 non-null  int64
 10  FLAG_LAST_APPL_PER_CONTRACT  1670214 non-null  object
 11  NFLAG_LAST_APPL_IN_DAY       1670214 non-null  int64
 12  RATE_DOWN_PAYMENT            774370 non-null   float64
 13  RATE_INTEREST_PRIMARY        5951 non-null     float64
 14  RATE_INTEREST_PRIVILEGED     5951 non-null     float64
 15  NAME_CASH_LOAN_PURPOSE       1670214 non-null  object
 16  NAME_CONTRACT_STATUS         1670214 non-null  object
 17  DAYS_DECISION                1670214 non-null  int64
 18  NAME_PAYMENT_TYPE            1670214 non-null  object
 19  CODE_REJECT_REASON           1670214 non-null  object
 20  NAME_TYPE_SUITE              849809 non-null   object
 21  NAME_CLIENT_TYPE             1670214 non-null  object
 22  NAME_GOODS_CATEGORY          1670214 non-null  object
 23  NAME_PORTFOLIO               1670214 non-null  object
 24  NAME_PRODUCT_TYPE            1670214 non-null  object
 25  CHANNEL_TYPE                 1670214 non-null  object
 26  SELLERPLACE_AREA             1670214 non-null  int64
 27  NAME_SELLER_INDUSTRY         1670214 non-null  object
 28  CNT_PAYMENT                  1297984 non-null  float64
 29  NAME_YIELD_GROUP             1670214 non-null  object
 30  PRODUCT_COMBINATION          1669868 non-null  object
 31  DAYS_FIRST_DRAWING           997149 non-null   float64
 32  DAYS_FIRST_DUE               997149 non-null   float64
 33  DAYS_LAST_DUE_1ST_VERSION    997149 non-null   float64
 34  DAYS_LAST_DUE                997149 non-null   float64
 35  DAYS_TERMINATION             997149 non-null   float64
 36  NFLAG_INSURED_ON_APPROVAL    997149 non-null   float64
dtypes: float64(15), int64(6), object(16)
memory usage: 471.5+ MB

In [9]:
previous_application.columns.tolist()

['SK_ID_PREV',
 'SK_ID_CURR',
 'NAME_CONTRACT_TYPE',
 'AMT_ANNUITY',
 'AMT_APPLICATION',
 'AMT_CREDIT',
 'AMT_DOWN_PAYMENT',
 'AMT_GOODS_PRICE',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'FLAG_LAST_APPL_PER_CONTRACT',
 'NFLAG_LAST_APPL_IN_DAY',
 'RATE_DOWN_PAYMENT',
 'RATE_INTEREST_PRIMARY',
 'RATE_INTEREST_PRIVILEGED',
 'NAME_CASH_LOAN_PURPOSE',
 'NAME_CONTRACT_STATUS',
 'DAYS_DECISION',
 'NAME_PAYMENT_TYPE',
 'CODE_REJECT_REASON',
 'NAME_TYPE_SUITE',
 'NAME_CLIENT_TYPE',
 'NAME_GOODS_CATEGORY',
 'NAME_PORTFOLIO',
 'NAME_PRODUCT_TYPE',
 'CHANNEL_TYPE',
 'SELLERPLACE_AREA',
 'NAME_SELLER_INDUSTRY',
 'CNT_PAYMENT',
 'NAME_YIELD_GROUP',
 'PRODUCT_COMBINATION',
 'DAYS_FIRST_DRAWING',
 'DAYS_FIRST_DUE',
 'DAYS_LAST_DUE_1ST_VERSION',
 'DAYS_LAST_DUE',
 'DAYS_TERMINATION',
 'NFLAG_INSURED_ON_APPROVAL']

In [10]:
application["TARGET"].value_counts()
#TARGET = 0 → loan did not default
#TARGET = 1 → client encountered payment difficulties

TARGET
0    282686
1     24825
Name: count, dtype: int64

In [11]:
application["TARGET"].value_counts(normalize=True)

TARGET
0    0.919271
1    0.080729
Name: proportion, dtype: float64

In [12]:
missing = (
    application.isna()
    .sum()
    .sort_values(ascending=False)
)

missing_percentage = (
    application.isna()
    .mean()
    .sort_values(ascending=False)
    * 100
)

missing_df = pd.DataFrame({
    "missing_count": missing,
    "missing_percentage": missing_percentage
})

missing_df.head(30)

                          missing_count  missing_percentage
COMMONAREA_AVG                   214865           69.872297
COMMONAREA_MODE                  214865           69.872297
COMMONAREA_MEDI                  214865           69.872297
NONLIVINGAPARTMENTS_MEDI         213514           69.432963
NONLIVINGAPARTMENTS_MODE         213514           69.432963
NONLIVINGAPARTMENTS_AVG          213514           69.432963
FONDKAPREMONT_MODE               210295           68.386172
LIVINGAPARTMENTS_AVG             210199           68.354953
LIVINGAPARTMENTS_MEDI            210199           68.354953
LIVINGAPARTMENTS_MODE            210199           68.354953
FLOORSMIN_MODE                   208642           67.848630
FLOORSMIN_AVG                    208642           67.848630
FLOORSMIN_MEDI                   208642           67.848630
YEARS_BUILD_AVG                  204488           66.497784
YEARS_BUILD_MODE                 204488           66.497784
YEARS_BUILD_MEDI                 204488           66.497784
OWN_CAR_AGE                      202929           65.990810
LANDAREA_MEDI                    182590           59.376738
LANDAREA_AVG                     182590           59.376738
LANDAREA_MODE                    182590           59.376738
BASEMENTAREA_MODE                179943           58.515956
BASEMENTAREA_MEDI                179943           58.515956
BASEMENTAREA_AVG                 179943           58.515956
EXT_SOURCE_1                     173378           56.381073
NONLIVINGAREA_MODE               169682           55.179164
NONLIVINGAREA_AVG                169682           55.179164
NONLIVINGAREA_MEDI               169682           55.179164
ELEVATORS_AVG                    163891           53.295980
ELEVATORS_MEDI                   163891           53.295980
ELEVATORS_MODE                   163891           53.295980

In [13]:
application["SK_ID_CURR"].duplicated().sum()
# SK_ID_CURR is the ID of the client, and it is unique for each row. Therefore, there are no duplicates in this column.

np.int64(0)

In [14]:
bureau["SK_ID_CURR"].duplicated().sum()

np.int64(1410617)

In [15]:
application["SK_ID_CURR"].nunique()

307511

In [16]:
bureau["SK_ID_CURR"].nunique()

305811

In [17]:
previous_application["SK_ID_CURR"].nunique()

338857

In [18]:
print(
    "Application customers:",
    application["SK_ID_CURR"].nunique()
)

print(
    "Customers in bureau:",
    bureau["SK_ID_CURR"].nunique()
)

print(
    "Customers in previous applications:",
    previous_application["SK_ID_CURR"].nunique()
)

Application customers: 307511
Customers in bureau: 305811
Customers in previous applications: 338857

In [19]:
selected_columns = [
    "SK_ID_CURR",
    "CODE_GENDER",
    "AMT_INCOME_TOTAL",
    "NAME_INCOME_TYPE",
    "NAME_EDUCATION_TYPE",
    "NAME_FAMILY_STATUS",
    "NAME_HOUSING_TYPE",
    "CNT_CHILDREN",
    "CNT_FAM_MEMBERS",
    "NAME_CONTRACT_TYPE",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "AMT_GOODS_PRICE",
    "DAYS_BIRTH",
    "DAYS_EMPLOYED",
    "OCCUPATION_TYPE",
    "EXT_SOURCE_1",
    "EXT_SOURCE_2",
    "EXT_SOURCE_3",
    "AMT_REQ_CREDIT_BUREAU_YEAR",
    "TARGET"
]

application[selected_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   SK_ID_CURR                  307511 non-null  int64
 1   CODE_GENDER                 307511 non-null  object
 2   AMT_INCOME_TOTAL            307511 non-null  float64
 3   NAME_INCOME_TYPE            307511 non-null  object
 4   NAME_EDUCATION_TYPE         307511 non-null  object
 5   NAME_FAMILY_STATUS          307511 non-null  object
 6   NAME_HOUSING_TYPE           307511 non-null  object
 7   CNT_CHILDREN                307511 non-null  int64
 8   CNT_FAM_MEMBERS             307509 non-null  float64
 9   NAME_CONTRACT_TYPE          307511 non-null  object
 10  AMT_CREDIT                  307511 non-null  float64
 11  AMT_ANNUITY                 307499 non-null  float64
 12  AMT_GOODS_PRICE             307233 non-null  float64
 13  DAYS_BIRTH                  307511 non-null  int64
 14  DAYS_EMPLOYED               307511 non-null  int64
 15  OCCUPATION_TYPE             211120 non-null  object
 16  EXT_SOURCE_1                134133 non-null  float64
 17  EXT_SOURCE_2                306851 non-null  float64
 18  EXT_SOURCE_3                246546 non-null  float64
 19  AMT_REQ_CREDIT_BUREAU_YEAR  265992 non-null  float64
 20  TARGET                      307511 non-null  int64
dtypes: float64(9), int64(5), object(7)
memory usage: 49.3+ MB

In [20]:
application["CODE_GENDER"].value_counts(dropna=False)

CODE_GENDER
F      202448
M      105059
XNA         4
Name: count, dtype: int64

In [21]:
application["NAME_INCOME_TYPE"].value_counts(dropna=False)

NAME_INCOME_TYPE
Working                 158774
Commercial associate     71617
Pensioner                55362
State servant            21703
Unemployed                  22
Student                     18
Businessman                 10
Maternity leave              5
Name: count, dtype: int64

In [22]:
application["NAME_EDUCATION_TYPE"].value_counts(dropna=False)

NAME_EDUCATION_TYPE
Secondary / secondary special    218391
Higher education                  74863
Incomplete higher                 10277
Lower secondary                    3816
Academic degree                     164
Name: count, dtype: int64

In [23]:
application["NAME_EDUCATION_TYPE"].value_counts(dropna=False)

NAME_EDUCATION_TYPE
Secondary / secondary special    218391
Higher education                  74863
Incomplete higher                 10277
Lower secondary                    3816
Academic degree                     164
Name: count, dtype: int64

In [24]:
application["NAME_CONTRACT_TYPE"].value_counts(dropna=False)

NAME_CONTRACT_TYPE
Cash loans         278232
Revolving loans     29279
Name: count, dtype: int64

In [25]:
application["NAME_HOUSING_TYPE"].value_counts(dropna=False)

NAME_HOUSING_TYPE
House / apartment      272868
With parents            14840
Municipal apartment     11183
Rented apartment         4881
Office apartment         2617
Co-op apartment          1122
Name: count, dtype: int64

In [26]:
application["OCCUPATION_TYPE"].value_counts(dropna=False)

OCCUPATION_TYPE
NaN                      96391
Laborers                 55186
Sales staff              32102
Core staff               27570
Managers                 21371
Drivers                  18603
High skill tech staff    11380
Accountants               9813
Medicine staff            8537
Security staff            6721
Cooking staff             5946
Cleaning staff            4653
Private service staff     2652
Low-skill Laborers        2093
Waiters/barmen staff      1348
Secretaries               1305
Realty agents              751
HR staff                   563
IT staff                   526
Name: count, dtype: int64

In [27]:
numeric_columns = [
    "AMT_INCOME_TOTAL",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "AMT_GOODS_PRICE",
    "DAYS_BIRTH",
    "DAYS_EMPLOYED",
    "EXT_SOURCE_1",
    "EXT_SOURCE_2",
    "EXT_SOURCE_3"
]

application[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
AMT_INCOME_TOTAL,307511.0,168797.919297,237123.146279,2.565000e+04,112500.000000,147150.000000,202500.000000,1.170000e+08
AMT_CREDIT,307511.0,599025.999706,402490.776996,4.500000e+04,270000.000000,513531.000000,808650.000000,4.050000e+06
AMT_ANNUITY,307499.0,27108.573909,14493.737315,1.615500e+03,16524.000000,24903.000000,34596.000000,2.580255e+05
AMT_GOODS_PRICE,307233.0,538396.207429,369446.460540,4.050000e+04,238500.000000,450000.000000,679500.000000,4.050000e+06
DAYS_BIRTH,307511.0,-16036.995067,4363.988632,-2.522900e+04,-19682.000000,-15750.000000,-12413.000000,-7.489000e+03
DAYS_EMPLOYED,307511.0,63815.045904,141275.766519,-1.791200e+04,-2760.000000,-1213.000000,-289.000000,3.652430e+05
EXT_SOURCE_1,134133.0,0.502130,0.211062,1.456813e-02,0.334007,0.505998,0.675053,9.626928e-01
EXT_SOURCE_2,306851.0,0.514393,0.191060,8.173617e-08,0.392457,0.565961,0.663617,8.549997e-01
EXT_SOURCE_3,246546.0,0.510853,0.194844,5.272652e-04,0.370650,0.535276,0.669057,8.960095e-01

In [28]:
application["DAYS_EMPLOYED"].describe()

count    307511.000000
mean      63815.045904
std      141275.766519
min      -17912.000000
25%       -2760.000000
50%       -1213.000000
75%        -289.000000
max      365243.000000
Name: DAYS_EMPLOYED, dtype: float64

Data quality issue identified:
DAYS_EMPLOYED contains a suspicious extreme value of 365243.

In [29]:
application[
    application["DAYS_EMPLOYED"] == 365243
].shape

(55374, 122)

In [30]:
application.shape

(307511, 122)

In [31]:
bureau.shape

(1716428, 17)

In [32]:
previous_application.shape

(1670214, 37)

In [33]:
application['TARGET'].value_counts(normalize=True)

TARGET
0    0.919271
1    0.080729
Name: proportion, dtype: float64

In [34]:
missing_df.head(20)

                          missing_count  missing_percentage
COMMONAREA_AVG                   214865           69.872297
COMMONAREA_MODE                  214865           69.872297
COMMONAREA_MEDI                  214865           69.872297
NONLIVINGAPARTMENTS_MEDI         213514           69.432963
NONLIVINGAPARTMENTS_MODE         213514           69.432963
NONLIVINGAPARTMENTS_AVG          213514           69.432963
FONDKAPREMONT_MODE               210295           68.386172
LIVINGAPARTMENTS_AVG             210199           68.354953
LIVINGAPARTMENTS_MEDI            210199           68.354953
LIVINGAPARTMENTS_MODE            210199           68.354953
FLOORSMIN_MODE                   208642           67.848630
FLOORSMIN_AVG                    208642           67.848630
FLOORSMIN_MEDI                   208642           67.848630
YEARS_BUILD_AVG                  204488           66.497784
YEARS_BUILD_MODE                 204488           66.497784
YEARS_BUILD_MEDI                 204488           66.497784
OWN_CAR_AGE                      202929           65.990810
LANDAREA_MEDI                    182590           59.376738
LANDAREA_AVG                     182590           59.376738
LANDAREA_MODE                    182590           59.376738

In [35]:
application[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
AMT_INCOME_TOTAL,307511.0,168797.919297,237123.146279,2.565000e+04,112500.000000,147150.000000,202500.000000,1.170000e+08
AMT_CREDIT,307511.0,599025.999706,402490.776996,4.500000e+04,270000.000000,513531.000000,808650.000000,4.050000e+06
AMT_ANNUITY,307499.0,27108.573909,14493.737315,1.615500e+03,16524.000000,24903.000000,34596.000000,2.580255e+05
AMT_GOODS_PRICE,307233.0,538396.207429,369446.460540,4.050000e+04,238500.000000,450000.000000,679500.000000,4.050000e+06
DAYS_BIRTH,307511.0,-16036.995067,4363.988632,-2.522900e+04,-19682.000000,-15750.000000,-12413.000000,-7.489000e+03
DAYS_EMPLOYED,307511.0,63815.045904,141275.766519,-1.791200e+04,-2760.000000,-1213.000000,-289.000000,3.652430e+05
EXT_SOURCE_1,134133.0,0.502130,0.211062,1.456813e-02,0.334007,0.505998,0.675053,9.626928e-01
EXT_SOURCE_2,306851.0,0.514393,0.191060,8.173617e-08,0.392457,0.565961,0.663617,8.549997e-01
EXT_SOURCE_3,246546.0,0.510853,0.194844,5.272652e-04,0.370650,0.535276,0.669057,8.960095e-01

In [37]:
target_count = application["TARGET"].value_counts()
target_pct = application["TARGET"].value_counts(normalize=True) * 100

print("TARGET count:")
print(target_count)

print("\nTARGET percentage:")
print(target_pct)

TARGET count:
TARGET
0    282686
1     24825
Name: count, dtype: int64

TARGET percentage:
TARGET
0    91.927118
1     8.072882
Name: proportion, dtype: float64

In [38]:
print("DAYS_EMPLOYED = 365243:")
print(
    (application["DAYS_EMPLOYED"] == 365243).sum()
)

DAYS_EMPLOYED = 365243:
55374

In [39]:
print("Application unique customers:",
      application["SK_ID_CURR"].nunique())

print("Bureau unique customers:",
      bureau["SK_ID_CURR"].nunique())

print("Previous application unique customers:",
      previous_application["SK_ID_CURR"].nunique())

print("\nApplication duplicate IDs:",
      application["SK_ID_CURR"].duplicated().sum())

Application unique customers: 307511
Bureau unique customers: 305811
Previous application unique customers: 338857

Application duplicate IDs: 0

In [40]:
selected_columns = [
    "SK_ID_CURR",
    "CODE_GENDER",
    "AMT_INCOME_TOTAL",
    "NAME_INCOME_TYPE",
    "NAME_EDUCATION_TYPE",
    "NAME_FAMILY_STATUS",
    "NAME_HOUSING_TYPE",
    "CNT_CHILDREN",
    "CNT_FAM_MEMBERS",
    "NAME_CONTRACT_TYPE",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "AMT_GOODS_PRICE",
    "DAYS_BIRTH",
    "DAYS_EMPLOYED",
    "OCCUPATION_TYPE",
    "EXT_SOURCE_1",
    "EXT_SOURCE_2",
    "EXT_SOURCE_3",
    "AMT_REQ_CREDIT_BUREAU_YEAR",
    "TARGET"
]

application[selected_columns].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   SK_ID_CURR                  307511 non-null  int64
 1   CODE_GENDER                 307511 non-null  object
 2   AMT_INCOME_TOTAL            307511 non-null  float64
 3   NAME_INCOME_TYPE            307511 non-null  object
 4   NAME_EDUCATION_TYPE         307511 non-null  object
 5   NAME_FAMILY_STATUS          307511 non-null  object
 6   NAME_HOUSING_TYPE           307511 non-null  object
 7   CNT_CHILDREN                307511 non-null  int64
 8   CNT_FAM_MEMBERS             307509 non-null  float64
 9   NAME_CONTRACT_TYPE          307511 non-null  object
 10  AMT_CREDIT                  307511 non-null  float64
 11  AMT_ANNUITY                 307499 non-null  float64
 12  AMT_GOODS_PRICE             307233 non-null  float64
 13  DAYS_BIRTH                  307511 non-null  int64
 14  DAYS_EMPLOYED               307511 non-null  int64
 15  OCCUPATION_TYPE             211120 non-null  object
 16  EXT_SOURCE_1                134133 non-null  float64
 17  EXT_SOURCE_2                306851 non-null  float64
 18  EXT_SOURCE_3                246546 non-null  float64
 19  AMT_REQ_CREDIT_BUREAU_YEAR  265992 non-null  float64
 20  TARGET                      307511 non-null  int64
dtypes: float64(9), int64(5), object(7)
memory usage: 49.3+ MB